### ISSUE TITLE
Script fails on grey-images

### ISSUE THREAD

**Issue by devneal** [FabriceCastel/gvcci#12] opened 2017-12-20 02:55 UTC
### Description

[This line](https://github.com/FabriceCastel/gvcci/blob/1ebc6c54c178abc900e26490f7edffd869cad066/src/extract.py#L30) throws the following error on [this image](https://archive-media-0.nyafuu.org/w/image/1432/48/1432487684222.png):
```
Traceback (most recent call last):
  File "src/extract.py", line 66, in <module>
    hsl_colors = get_pixels_for_image(img_file_path)
  File "src/extract.py", line 30, in get_pixels_for_image
    img_hsl = hasel.rgb2hsl(img_rgb[:,:,0:3])
IndexError: too many indices for array
```

### Steps to Reproduce

Run `./gvcci.sh [path_to_image]`

### Additional Information

The documentation for `skimage.io.imread` reads:
```
    Returns
    -------
    img_array : ndarray
        The different colour bands/channels are stored in the
        third dimension, such that a grey-image is MxN, an
        RGB-image MxNx3 and an RGBA-image MxNx4.
```
Which leads me to believe that the line will produce unexpected results on all grey-images and RGBA-images.

**Comment by FabriceCastel** [comment] 2017-12-20 03:47
You were right about the cause of the bug. I pushed [a commit](https://github.com/FabriceCastel/gvcci/commit/e20b8bedbcdf26c7783920e0cc215a06eca50e3d) that should handle that case.

I was able to replicate the error using your image, then to get a successful result after the fix, so this looks good to me. For the sake of completeness, please confirm that this change did resolve the issue for you before I close this one out :)

Thanks for the bug report!

**Comment by devneal** [comment] 2017-12-20 03:53
Works for me too. Thanks.

**Closed as completed** 2017-12-20 12:05 UTC
